FROM python:3.9-slim

WORKDIR /app

# Install basic dependencies
RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Install Python packages
RUN pip install --no-cache-dir \
    yt-dlp==2023.12.30 \
    openai-whisper==20231117 \
    googletrans==3.1.0a0 \
    ffmpeg-python==0.2.0

# Copy the Python script
COPY ./src/lib/python /app/python

# Set the entrypoint
ENTRYPOINT ["python3"] 